
logging:
  #日志存储地址
  file: "logs/app-client.log"
info:
  name : "代理客户端"

server:
  #端口号
  port: 8888
  servlet:
    context-path: /
#  address: client1.com

#  ssl:
#    key-store: classpath:key/client1.keystore
#    key-alias: client1.com
#    key-store-password: changeit

spring:
  mvc:
    view:
      # 页面默认前缀目录
      prefix: /WEB-INF/jsp/
      # 响应页面默认后缀
      suffix: .jsp